# Generated by Django 4.1.2 on 2022-10-07 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_familiar_fecha_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiar',
            name='fecha_nacimiento',
        ),
    ]
